### ISSUE TITLE
problem when run command "composer install"

### ISSUE THREAD

**Issue by rahebsaeed** [themeselection/materio-bootstrap-html-laravel-admin-template-free#1]
### Steps to reproduce

composer install
No composer.lock file present. Updating dependencies to latest instead of installing from lock file. See https://getcomposer.org/install for more information.                                                                                      
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires php ^8.1 but your php version (7.4.33) does not satisfy that requirement.
  Problem 2
    - Root composer.json requires laravel/sanctum ^3.2 -> satisfiable by laravel/sanctum[v3.2.0, ..., 3.x-dev].
    - laravel/sanctum[v3.2.0, ..., 3.x-dev] require php ^8.0.2 -> your php version (7.4.33) does not satisfy that requirement.
  Problem 3
    - laravel/framework[v10.25.0, ..., 10.x-dev] require php ^8.1 -> your php version (7.4.33) does not satisfy that requirement.
    - Root composer.json requires laravel/framework ^10.24.2 -> satisfiable by laravel/framework[v10.25.0, ..., 10.x-dev].

### What is expected?

not install folder vendor

### What is actually happening?

not install folder vendor

**Comment by smitbhalodiya** [comment]
Hi @rahebsaeed,

Thanks for getting in touch with us!!

You are facing challenges installing Composer due to compatibility issues between PHP, Laravel and Sanctum versions.
To address this, we advise you to update the versions of PHP, Laravel and Sanctum on your local system according to the requirements specified in the composer.json file.
This step is crucial for ensuring that all components work seamlessly together, thereby resolving the installation difficulties you're facing.

Regards~
