### ISSUE TITLE
How to Remove Fake Database and Use Real API 

### ISSUE THREAD

**Issue by ghost** [themeselection/materio-bootstrap-html-laravel-admin-template-free#4]
### What problem does this feature solve?

The support video shows a help center for React and Nextjs where the first article is about the removal of Materio's fake database and using a real API.
I can't find those instructions for the Bootstrap HTML Laravel Template and there's no search option in its documentation.

### What does the proposed solution look like?

Add instructions for removing the fake database from the Bootstrap HTML Laravel Template and using a real API.

**Comment by smitbhalodiya** [comment]
Hello @Mattimus13,

Thank you so much for your valuable suggestion about adding a search option in the documentation and the feedback regarding the support video. We will certainly consider this and work on it for future updates.

Regarding your question about removing the fake database, we have used the DataTables library to display demo data in the template for demonstration purposes. However, if you wish to use a real API instead of the demo data, you can absolutely do so. The official documentation of DataTables provides a guide on how to integrate your own API. You can refer to that to integrate a real API into your project. https://datatables.net/reference/type/DataTables.Api

Let me know if you have any other queries.

**Comment by ghost** [comment]
Hi Smit,

Thanks  for getting back to me.
I'd like to have the app work properly with a payment gateway like Stripe.

  1.
I need help setting up the eCommerce API so those pages are pointing to my mysql database.
  2.
I also require assistance integrating Stripe for payments.

So basically, I'd to be able to add a product, pay for it with a credit card and then receive an invoice.
Is this a project you'd be interested in?
If so, what will it cost?

Kind regards,
Matt
________________________________

**Comment by smitbhalodiya** [comment]
Hello @ghost

Please note that we only provide the UI design for our templates. Any customization or back-end functionality, such as setting up the eCommerce API to connect to your MySQL database or integrating payment gateways like Stripe, would need to be handled on your end.

However, if you're looking for help with customization, you can find more information and hire our team by visiting this [link](https://themeselection.com/hire-us/). If you proceed, our team will get in touch with you within 1 to 2 working days.

Also, kindly note that the features you're requesting are not available in our free product. You might want to check out our Pro version, which includes more advanced features: [Materio Dashboard Pro.](https://themeselection.com/item/materio-dashboard-pro-laravel/)
